num = int(input("Enter a number..."))
print(num)
print(num * 2)
print(num * 3)
print(num * 4)
print(num * 5)
print(num * 6)
print(num * 7)
print(num * 8)
print(num * 9)
print(num * 10)
print(num * 11)
print(num * 12)